### ISSUE TITLE
Example of pool?

### ISSUE THREAD

**Issue by krunalshah68** [Kikobeats/browserless#21]
I'm trying to launch 100 instance of browser at the same time to load test my website. Any example for that using browserless pool?

**Comment by Kikobeats** [comment]
Just the thing that's different is how to create the browserless instance:

**without pool**

```
const createBrowserless = require('browserless')
const browserless = createBrowserless()
```

**with pool**

```
const createBrowserless = require('browserless')
const browserless = createBrowserless.pool()
```

Can you check that [examples](https://github.com/Kikobeats/browserless/tree/master/examples) as working as expected? we can add a specific flag for enabling pool

**Comment by krunalshah68** [comment]
Thank you for such an early reply @Kikobeats :+1: 
Yeah but I'm trying to use that created **pool** multiple times.
Here is the code:
```
const createBrowserless = require('browserless')
const browserless = createBrowserless.pool({
	headless: false,
	poolOpts: {
		min: 1,
		max: 5
	}
})

;(async () => {
	for (var index = 0; index < 5; index++) {
		const myTask = browserInstance => {
			return new Promise(async (resolve, reject) => {
				try {
					// do something with the client and resolve/reject
					const page = await browserInstance.page();
					browserInstance.goto(page, {
						url: 'http://google.com',
						timeout: 12000
					})
					resolve();
				} catch (error) {
					console.log(error)
					reject();
				}
			})
		}
		try {
			const page = await browserless.pool.use(myTask);
			console.log(page);
		} catch (error) {
			console.log(error);
		}
	}
})()
```

Please let me know if I'm doing anything wrong.

**Comment by Kikobeats** [comment]
You can't get a page from a pool of browserless; Instead, get the browser instance and the do what you want:

```js
const createBrowserless = require('browserless')
const browserlessPool = createBrowserless.pool()

// get a browserless instance from the pool
browserless.pool(browserless => {
  // get a page from the browser instance
  const page = await browserless.page()
})
```

I close the issue but please continue chatting

**Comment by Kikobeats** [comment]
Yes 😅

**Comment by krunalshah68** [comment]
Well that's throwing this error. :(
```
(node:9660) UnhandledPromiseRejectionWarning: TypeError: browserlessPool.pool is not a function
    at /usr/browserless/index.js:38:18
    at Object.<anonymous> (/usr/browserless/index.js:46:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
```

**Comment by Kikobeats** [comment]
ops, looks like you need to call `pool.use`

```
'use strict'

const createBrowserless = require('..')
const browserlessPool = createBrowserless.pool()

// get a browserless instance from the pool
browserlessPool.pool.use(async browserless => {
  console.log('browserless', browserless)
  // get a page from the browser instance
  const page = await browserless.page()
  console.log('page', page)
})
```

that's could bit improved a bit

**Comment by krunalshah68** [comment]
exactly! Thanks @Kikobeats  :+1:
